# 配置端口
server:
  port: 9090
  tomcat:
    uri-encoding: utf-8

# 绑定mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: xyz.ibudai.entity
  # 控制台打印 sql 语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# pageHepler分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
