spring:
  # Redis 缓存
  redis:
    host: 10.231.6.65
    port: 6379
    password: 123456
    timeout: 1800000
    lettuce:
      pool:
        max-idle: 8
        max-active: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms
  # 邮件配置
  mail:
    host: smtp.163.com
    username: great__jin@163.com
    password: xxxxxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          starttls.required: true

# Minio数据库
minio:
  endpoint: http://10.231.6.65:9000
  accessKey: minioadmin
  secretKey: minioadmin

